### login
POST http://localhost:4000/user/login
Content-Type: application/json

{
    "userName":"DucAnh",
    "password":"cnoGJC76"
}

### get task by user
GET http://localhost:4000/task
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTVhYTlmNWZjZjE5MmM2MGQ2NTI1NiIsInVzZXJOYW1lIjoiRHVjQW5oIiwiaWF0IjoxNjkyODUxNDY4fQ.uwQBE-ozAy1tWqEyAE23C2LjrPR1zY3CypmIzErCOs4

### create new task
POST http://localhost:4000/task
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTVhYTlmNWZjZjE5MmM2MGQ2NTI1NiIsInVzZXJOYW1lIjoiRHVjQW5oIiwiaWF0IjoxNjkyODUxNDY4fQ.uwQBE-ozAy1tWqEyAE23C2LjrPR1zY3CypmIzErCOs4

{
    "taskTitle":"Test task create title",
    "taskNote":"test note string",
    "taskComment":"test comment string",
    "isDaily":"false",
    "category":"mission everyday",
    "deadlineTime":""
}